baseURL = "https://bentowali.com/"
languageCode = "en-us"
title = "Ben Towali"
theme = "smol"

# Theme settings
[params]
	dateFmt = "02/01/2006"

[menu]
	[[menu.main]]
		identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
	[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

	[[menu.footer]]
		name = "Gitlab"
		url = "https://gitlab.com/BenTowali"
		weight = 1
